apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  labels:
    app: mysqlpod
spec:
  containers:
    - name: mysql
      image: 'mysql:5.7'
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
